# A docker container for our API-level Django project.
#
# It serves files using Apache's mod_wsgi-express.
api:
    container_name: api
    image: omattei/restful-django

    # we want to link to an external mysql docker container
    external_links:
        - mysql:db
    ports:
        - "8003:8000"
    volumes:
        - ./api:/app
    command: /app/deploy_server.sh

# A docker container for our API-level static files
#       (e.g. stylesheets, images, JavaScript)
#
# It serves files using the lightweight web server lighttpd.
#
# In production, this would be served up on a separate
# domain/server, but for development we will spin up
# this server on port 8001.
api_static:
    container_name: api_static
    image: sebp/lighttpd
    volumes:
        - ./api/static:/var/www/localhost/htdocs/static
    ports:
        - "8002:80"

# A docker container for our user experience-level Django project.
#
# It serves files using Apache's mod_wsgi-express.
ux:
    container_name: ux
    image: tp33/django

    # we want to link to an external mysql docker container
    links:
        - api
    ports:
        - "8001:8000"
    volumes:
        - ./ux:/app
    command: /app/deploy_server.sh

# A docker container for our web-facing Django project.
#
# It serves files using Apache's mod_wsgi-express.
www:
    container_name: www
    image: tp33/django

    # we want to link to an external mysql docker container
    links:
        - ux
    ports:
        - "8000:8000"
    volumes:
        - ./ux:/app
    command: /app/deploy_server.sh
