isa_app:
   container_name: isa_app
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "80:8000"
   volumes:
       # figure out why this works
    - ../isa/app:/app
   command: /app/deploy_server
