isa_app:
   container_name: isa_app
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "80:8000"
   volumes:
      - $HOME/dev/isa/app:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes --log-to-terminal /app/isa_app/isa_app/wsgi.py --working-directory /app/isa_app"
